name=input("Enter your name: ")
print("Hello, " + name + "! Welcome to the project.")
age=input("Enter your age: ")
print("You are " + age + " years old.")
college=input("Enter your college name: ")
print("You study at " + college + ".")
department=input("Enter your department: ")
print("You are in the " + department + " department.")
